### PR TITLE
New Branch added DaanVeer

### PR DESCRIPTION
**Pull request by shivam1192**
The branch consists of a directory Examples which has my Money ligos hackathon submission with biconomy inbuilt.

### CODE REVIEW

**Comment by tarun1475** [comment]
@shivam1192 i am not able to see the project.

**Comment by shivam1192** [comment]
@tarun1475 follow up these steps:
1.Clone project and ensure to have node and Ganache platform.
2.Run npm install to install all dependency.
3.Add your MongoDB cluster link (MONGOOSE_CONNECT), LocalHost (LOCALHOST), access token secret (ACCESS_TOKEN), and refresh token secret (REFRESH_TOKEN) in an environment variable in backend folder.
4.run cd backend and node app.js, this will start your server
5.In frontend folder run npm start, this will start your application on localhost  3000. Run application ***in Mozilla Firefox because it used cookies to store refresh token.

**Comment by shivam1192** [comment]
Btw actual repo of this project is: https://github.com/shivam1192/DaanVeer

**Comment by tarun1475** [comment]
> @tarun1475 follow up these steps:
> 1.Clone project and ensure to have node and Ganache platform.
> 2.Run npm install to install all dependency.
> 3.Add your MongoDB cluster link (MONGOOSE_CONNECT), LocalHost (LOCALHOST), access token secret (ACCESS_TOKEN), and refresh token secret (REFRESH_TOKEN) in an environment variable in backend folder.
> 4.run cd backend and node app.js, this will start your server
> 5.In frontend folder run npm start, this will start your application on localhost 3000. Run application ***in Mozilla Firefox because it used cookies to store refresh token.

Surely i will do it. 
For now would be great if you follow the guidelines and we need to review your code first here only and want to make it available publicly.

**Comment by shivam1192** [comment]
Yeah sure! I had made a pull request according to the Code submission guidelines only.

**Pull request closed without merging**
